name: TF Plan

on:
  push:
env:
    GCP_SA_KEY: ${{secrets.GCP_SA_KEY}}
jobs:
  quality:
    runs-on: ubuntu-latest
        
    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Google Cloud Auth
          uses: 'google-github-actions/auth@v2'
          with:
            credentials_json: '${{secrets.GCP_SA_KEY}}'
            project_id: 'patricio-poc-1'

        - name: Install terraform
          run: |
            sudo apt-get install wget unzip -y
            release=`curl -s https://api.github.com/repos/hashicorp/terraform/releases/latest |  grep tag_name | cut -d: -f2 | tr -d \"\,\v | awk '{$1=$1};1'`
            wget https://releases.hashicorp.com/terraform/${release}/terraform_${release}_linux_amd64.zip
            unzip terraform_${release}_linux_amd64.zip
            sudo mv terraform /usr/bin/terraform

        - name: Plan
          run: |
            terraform init
            terraform plan